# Generated by Django 4.0.5 on 2022-06-12 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vNumber', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('vType', models.CharField(choices=[('4', 'Four Wheeler'), ('3', 'Three Wheeler'), ('2', 'Two Wheeler')], default=4, max_length=20)),
                ('vModel', models.TextField()),
                ('vDescription', models.TextField()),
            ],
        ),
    ]
